# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: WazeRouteCalculator

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '2.7', '3.6', '3.8', '3.10' ]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python  ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: ${{ matrix.python-version }} - Install dependencies 
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest coveralls mock requests_mock 
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: ${{ matrix.python-version }} - Test with pytest
      run: |
        pytest tests.py
